### ISSUE TITLE
Include license text in a source tarball

### ISSUE THREAD

**Issue by tyrylu** [festvox/speech_tools#15]
Hello.
Would it be possible to include the license text in a release tarball and as a separate file in the repository? It would help the packaging effords very much.

**Comment by festvox** [comment]
Its in the README.md, or do you mean as a COPYING file with just the license?

**Comment by tyrylu** [comment]
Yes, as a separate copying file. It makes packaging festival somewhat easier, you don't have to either mark the entire readme as a license file or create the separate license manually.

**Comment by festvox** [comment]
OK, done

**Comment by tyrylu** [comment]
Thank you.
