### ISSUE TITLE
 wagon: -omp_nthreads ignored: not support in this build. wagon script status: INCORRECT

### ISSUE THREAD

**Issue by baaslaawe** [festvox/speech_tools#2]
hello 👍

when i try to install i got this errorr

(make test)
**wagon: -omp_nthreads ignored: not support in this build.
wagon script status: INCORRECT**

and also i got 

RMSE 37.2237 Correlation is 0.4856 Mean (abs) Error 28.7110 (23.7016)
**wagon: -omp_nthreads ignored: not support in this build.**

**Comment by VZIKL** [comment]
@baaslaawe 
please provide more information
such as 
OS , More  information about compiled error, etc.

**Comment by awbcmu** [comment]
This error is really in the make test script, the test script assume omp is supported, but when it isn't there is a mismatch in the output with the completely appropriate error message.  The answer might be allow for multiple valid outputs in the make test script, but we don't have that anywhere else at present.

**Comment by saikrishnarallabandi** [comment]
closing.
