### ISSUE TITLE
Complement build system with meson?

### ISSUE THREAD

**Issue by zeehio** [festvox/speech_tools#37]
Would you consider to review a pull request that allowed the user to build speech_tools, festival and festvox using the meson build system (https://mesonbuild.com/)?

The current build system:
- has race conditions when building in parallel
- for festival and festvox it requires that speech tools is found at a specific parent directory
- does not honor --prefix
- does not allow out of source builds (i.e. the directory where speech tools is built must be the directory where the sources are)
- cross-compilation does not seem straightforward

meson is a nice (and modern) alternative. It should be possible to have both build systems (the current one and meson) and if meson works better eventually remove the current one in a future version.

Thanks for any feedback!

**Comment by lenzo-duo** [comment]
We talked it over a bit, and while you make some valid points, we have seen build systems come and go before, and are also worried that the two might get out of sync. You might consider a sister repository containing the build system, or adding a patch which expands the meson pieces which we could potentially include in the distribution itself. At the moment we would like to be somewhat conservative with respect to such a big change, but we don't want to shut down your efforts. Personally, I would like the benefits you raise.

**Comment by lenzo-duo** [comment]
Yes. But we must take care to keep things synced going forward.

**Comment by lenzo-duo** [comment]
Done -- thanks
